### PR TITLE
Rename script for binary installs.

### PR DESCRIPTION
**Pull request by steveworley**
These binaries are not included during the scaffold tooling install.

```
$ ls -la vendor/bin | grep govcms-enable_module | wc -l
0
$ ls -la vendor/bin | grep govcms-update_site_alias | wc -l
0
```

This is causing a deployment problem with the scaffold update to leverage the chunked deploy scripts.

```
bash: /app/vendor/bin/govcms-update_site_alias: No such file or directory
```

Oddly - that the scripts and composer json match in master, however if you download the latest release these scripts are named `govcms-enable-module` and `govcms-update-site-alias` respectively. I'm not sure what causes the rename here, can't find anything specifically about it in composer bin information - but we need these executable.

### CODE REVIEW

**Comment by simesy** [comment]
Weird problem... Like the tests

**Comment by steveworley** [comment]
Yeah super weird, composer is installing the latest version.

```
name     : govcms/scaffold-tooling
descrip. : A variety of standard config, scripts and packages to support GovCMS scaffold.
keywords : 
versions : * 2.0.5
type     : library
license  : GNU General Public License v2.0 or later (GPL-2.0-or-later) (OSI approved) https://spdx.org/licenses/GPL-2.0-or-later.html#licenseText
homepage : 
source   : [git] https://github.com/govCMS/scaffold-tooling.git 138dd74fded698bb63bfc9ef016895616a23a8ed
dist     : [zip] https://api.github.com/repos/govCMS/scaffold-tooling/zipball/138dd74fded698bb63bfc9ef016895616a23a8ed 138dd74fded698bb63bfc9ef016895616a23a8ed
path     : /app/vendor/govcms/scaffold-tooling
names    : govcms/scaffold-tooling

support
source : https://github.com/govCMS/scaffold-tooling/tree/2.0.5
issues : https://github.com/govCMS/scaffold-tooling/issues
```

And the file exists:

```
$ ls vendor/govcms/scaffold-tooling/scripts/deploy
govcms-enable-modules
govcms-update-site-alias
```
and bin of my installed version:
```
"bin": [
        "scripts/deploy/govcms-enable_modules",
        "scripts/deploy/govcms-update_site_alias"
    ]
```

**Comment by simesy** [comment]
When i install i get https://github.com/govCMS/scaffold-tooling/tree/2.0.5 and it appears this has issues.

Everything is `-` here https://github.com/govCMS/scaffold-tooling/tree/2.0.5/scripts/deploy
But composer.json uses `_` incorrectly https://github.com/govCMS/scaffold-tooling/blob/2.0.5/composer.json#L39

**Comment by simesy** [comment]
So yeah the fix looks right, it's just weird that 2.0.5 specifically got some name changes? Anyway...

**Comment by steveworley** [comment]
Yeah was just poking around to find that out too. Not sure what happened with 2.0.5 tag, I'll roll back the rename and just add the tests with this hotfix and cut a new 2.0.6 hotfix tag of master.

**Comment by steveworley** [comment]
```
$ composer show govcms/scaffold-tooling
name     : govcms/scaffold-tooling
descrip. : A variety of standard config, scripts and packages to support GovCMS scaffold.
keywords : 
versions : * 2.0.6
type     : library
license  : GNU General Public License v2.0 or later (GPL-2.0-or-later) (OSI approved) https://spdx.org/licenses/GPL-2.0-or-later.html#licenseText
homepage : 
source   : [git] https://github.com/govCMS/scaffold-tooling.git 509477775f89cf9bfeef4677d5adace0ad853541
dist     : [zip] https://api.github.com/repos/govCMS/scaffold-tooling/zipball/509477775f89cf9bfeef4677d5adace0ad853541 509477775f89cf9bfeef4677d5adace0ad853541
path     : /app/vendor/govcms/scaffold-tooling
names    : govcms/scaffold-tooling
```

```
$ ls vendor/bin | grep govcms-update_site_alias -c
1
```

This doesn't need to be a hotfix now, we can merge this to develop for the next release to improve testing.

**Comment by fubarhouse** [comment]
Let me know if this is ready to review! 🙂

**Comment by steveworley** [comment]
Feel free to review @fubarhouse, this PR just adds some additional testing to make sure the composer install process puts the scripts in the expected locations.

This is pretty important to verify each time as the other pieces to govcms will expect these scripts to be there.

**Comment by fubarhouse** [comment]
Sweet. I tested this last week.

**Pull request merged**
