### PR TITLE
[DEVOPS-279] Required Drush 12.

### PR DESCRIPTION
**Pull request by sonnykt**
Companion PRs:
* GovCMS: https://github.com/govCMS/GovCMS/pull/923
* GovCMS Lagoon: https://github.com/govCMS/lagoon/pull/371
* GovCMS Scaffold: https://github.com/govCMS/scaffold/pull/74
* Scaffold tooling: https://github.com/govCMS/scaffold-tooling/pull/289

### CODE REVIEW

**Review by steveworley — APPROVED** [review]

**Comment by steveworley** [comment]
Hey @sonnykt can you review the failing test?

**Comment by sonnykt** [comment]
hey @steveworley 
```
# Your requirements could not be resolved to an installable set of packages.
#
#   Problem 1
#     - Root composer.json requires govcms/scaffold-tooling 10.x-master-dev -> satisfiable by govcms/scaffold-tooling[dev-10.x-master].
#     - govcms/scaffold-tooling dev-10.x-master requires drush/drush ~9 || ~10 || ~11 -> found drush/drush[9.0.0-alpha1, ..., 9.x-dev, 10.0.0-alpha1, ..., 10.x-dev, 11.0.0-rc1, ..., 11.x-dev] but it conflicts with your root composer.json require (^12).
```
It seems that when CI builds scaffold it still requires `govcms/scaffold-tooling dev-10.x-master` which doesn't have Drush 12.

**Comment by steveworley** [comment]
> hey @steveworley
> 
> ```
> # Your requirements could not be resolved to an installable set of packages.
> #
> #   Problem 1
> #     - Root composer.json requires govcms/scaffold-tooling 10.x-master-dev -> satisfiable by govcms/scaffold-tooling[dev-10.x-master].
> #     - govcms/scaffold-tooling dev-10.x-master requires drush/drush ~9 || ~10 || ~11 -> found drush/drush[9.0.0-alpha1, ..., 9.x-dev, 10.0.0-alpha1, ..., 10.x-dev, 11.0.0-rc1, ..., 11.x-dev] but it conflicts with your root composer.json require (^12).
> ```
> 
> It seems that when CI builds scaffold it still requires `govcms/scaffold-tooling dev-10.x-master` which doesn't have Drush 12.

Yeah — I saw that yesterday when I was trying to unblock the pipeline. I think we accept the automated test failure for now and resolve once we get this through to master.

Thanks for reviewing.

**Comment by simesy** [comment]
If you're on PaaS debugging drush launcher and find yourself here, you need to apply soemthing lik this to your site https://github.com/govCMS/scaffold/commit/5ac3b14ceb5bfa126cb438a5b97d99eeee384b20

**Pull request merged**
